-- Initial Admin User Setup
-- This is a one-time setup script to create the admin user
-- Username: sahar
-- Password: 240397Sm!
-- Password hash generated with bcrypt (cost factor 10)

INSERT INTO users (username, password_hash)
VALUES ('sahar', '$2b$10$xJ3qYZvK5Y7dKZQF.ZLQ0.zN8VWB8GxLj8X7rH8KqYpYxC3ZxY7nK')
ON CONFLICT (username) DO NOTHING;

-- Note: The actual password hash will be generated by the application
-- This is a placeholder. Run the setup script through the app to create the real hash.
